import React from 'react';

function Home() {
  return (
    <div>
      <style jsx> {`
        `}
      </style>
      <div className='home'>
        <h3>
            Hi, I'm Daniel Lira, Welcome to My portfolio. Please feel free to click some of the links above to browse a few of my achievements, view my resume, and find a bit more information including how to cantact me.
        </h3>
      </div>
    </div>
  );
}
  
export default Home;